version: "3.8"

services:
  db:
    image: postgres
    container_name: crypto_db
    environment:
      - POSTGRES_USER=crypto_bot
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DATABASES=crypto_bot
    volumes:
      - postgresql_db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: CryptoBot/CI/Docker/Dockerfile
    container_name: crypto_bot
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  ngrok:
    image: wernight/ngrok
    links:
      - web
    command: sh -c "ngrok authtoken ${NGROK_AUTHTOKEN} && ngrok http --region=us --hostname=${NGROK_HOST} web:8000"

volumes:
  postgresql_db:
