version: "3.8"

services:
  db:
    image: postgres
    container_name: crypto_db
    environment:
      - POSTGRES_USER=crypto_bot
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DATABASES=crypto_bot
    ports:
      - 5454:5432
    volumes:
      - postgresql_db:/var/lib/postgresql/data
      - ./:/app


volumes:
  postgresql_db:
