# Generated by Django 3.2.5 on 2021-07-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgprofile',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
