# Generated by Django 3.2.5 on 2021-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tgprofile_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgprofile',
            name='second_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tgprofile',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
